# Generated by Django 4.1.6 on 2023-02-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_author_contact_chat_message_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='messages',
        ),
    ]
